### PR TITLE
Set rooms and dropped arrival coffee.

### PR DESCRIPTION
**Pull request by tnabtaf**

### CODE REVIEW

**Comment by martenson** [comment]
no coffee?

**Comment by tnabtaf** [comment]
No upon arrival.  If staying at the UGH, breakfast is included.  That and
dropping the arrival drinks allows us to add a dinner.

**Comment by Slugger70** [comment]
There are two coffee shops in the building and one directly across the road.. (I've been looking.. I'm a little bit obsessed with coffee.. ;) )

**Comment by martenson** [comment]
we might survive after all then :)

**Pull request merged**
